import json
import random
import asyncio
from tqdm import tqdm
from openai import AsyncOpenAI

API_KEY = "#"
BASE_URL = "https://api.deepseek.com"
MODEL = "deepseek-chat"

TOTAL = 10000
BATCH_SIZE = 10
CONCURRENCY = 20

# ====== style vocab ======
STYLE_VOCAB =  [
    "oil painting",
    "thick brushstrokes",
    "warm tone",
    "vibrant colors",
    "neon lights",
    "realistic photography",
    "wet texture",
    "cinematic",
    "ink wash painting",
    "minimalist",
    "elegant lines",
    "monochrome",
    "watercolor",
    "soft pastel",
    "dreamy glow",
    "gentle texture",
    "sci-fi",
    "3D render",
    "cosmic glow",
    "ultra realistic",
    "japanese anime",
    "soft shading",
    "hand drawn",
    "dark fantasy",
    "baroque",
    "dramatic shadow",
    "stone texture",
    "nordic style",
    "natural light",
    "clean",
    "steampunk",
    "brass metal",
    "rust texture",
    "industrial",
    "impressionism",
    "brush strokes",
    "bright tone",
    "warm glow",
    "gufeng",
    "ethereal glow",
    "silk texture",
    "traditional art",
    "8-bit pixel",
    "retro game",
    "nostalgic",
    "pixelated",
    "close-up photography",
    "sharp focus",
    "vivid",
    "wasteland",
    "dystopian",
    "gritty texture",
    "dark tone",
    "cartoon",
    "kawaii",
    "soft color",
    "simple background",
    "cute",
    "landscape photography",
    "cold tone",
    "wide angle",
    "vintage oil painting",
    "elegant",
    "classical",
    "glossy metal",
    "LED glow",
    "3D",
    "chinese ink art",
    "serene",
    "pop art",
    "high saturation",
    "retro vibe",
    "clean lines",
    "realistic armor",
    "dramatic light",
    "epic",
    "surrealism",
    "blue tone",
    "glowing scales",
    "soft light",
    "street photography",
    "film grain",
    "candid",
    "fantasy",
    "vintage leather",
    "candle light",
    "mystical runes",
    "ukiyo-e",
    "traditional",
    "flat color",
    "classic japanese art",
    "realistic landscape",
    "cyber gufeng",
    "neon katana",
    "futuristic",
    "wildlife photography",
    "cold light",
    "arctic",
    "classic european",
    "warm light",
    "wooden texture",
    "cozy",
    "anime cel shading",
    "glitter",
    "bright color",
    "dramatic landscape",
    "fiery color",
    "epic composition",
    "cinematic light",
    "minimalist portrait",
    "soft focus",
    "simple",
    "brass texture",
    "retro",
    "meticulous painting",
    "delicate lines",
    "sci-fi fantasy",
    "glowing plants",
    "purple sky",
    "1950s vintage",
    "neon glow",
    "high fantasy",
    "green tone",
    "detailed costume",
    "macro photography",
    "moody tone",
    "imperial gufeng",
    "red gold",
    "grand architecture",
    "low poly",
    "geometric art",
    "pastel color",
    "minimalist 3D",
    "modern",
    "noir photography",
    "dim light",
    "black white",
    "grainy",
    "atmospheric",
    "mythical art",
    "fiery glow",
    "dynamic pose",
    "romantic landscape",
    "dark cyberpunk",
    "digital glow",
    "rustic",
    "high fashion",
    "sharp",
    "cartoon fantasy",
    "majestic",
    "gothic horror",
    "dark elegant",
    "mysterious",
    "nature macro",
    "fresh green",
    "80s retro",
    "pixel vibe",
    "chinese landscape",
    "ethereal mist",
    "grand",
    "cosmic fantasy",
    "starry texture",
    "vintage warm",
    "cozy photography",
    "rustic texture",
    "feudal japan",
    "dark stealth",
    "cinematic",
    "fantasy landscape",
    "sunlight glow",
    "black white photography",
    "high contrast",
    "artistic",
    "fantasy geology",
    "glowing gems",
    "reflective",
    "magical",
    "ins photography",
    "bright tone",
    "vintage sci-fi",
    "gear details",
    "floral painting",
    "rich color",
    "detailed texture",
    "military sci-fi",
    "gritty",
    "post-impressionism",
    "chinese classical",
    "3D cartoon",
    "smooth texture",
    "adorable",
    "alpine landscape",
    "clear light",
    "vintage cabaret",
    "glamorous",
    "fairy tale",
    "whimsical",
    "tiny details",
    "city photography",
    "night neon",
    "reflection",
    "purple glow",
    "ancient ruins",
    "food photography",
    "white background",
    "norse medieval",
    "rugged wood",
    "stormy sea",
    "historical",
    "soft aesthetic",
    "gradient color",
    "peaceful",
    "smooth",
    "sci-fi anime",
    "white tone",
    "archaeological photography",
    "weathered",
    "textured",
    "day of the dead",
    "intricate patterns",
    "festive",
    "modern minimalist",
    "clean composition",
    "japanese yokai",
    "glowing tails",
    "mystical",
    "sci-fi utopia",
    "glass metal",
    "glowing light",
    "golden light",
    "vintage carnival",
    "fantasy elemental",
    "mossy texture",
    "rugged",
    "minimalist home",
    "lacquer texture",
    "intricate details",
    "fantasy nature",
    "night scene",
    "modern corporate office",
    "professional",
    "floral landscape",
    "sunlight",
    "vintage still life",
    "dark stealth",
    "silhouette",
    "mirror landscape",
    "clear light",
    "k-pop anime",
    "spotlight",
    "high quality",
    "historical fantasy",
    "forge fire",
    "warm glow",
    "cyberpunk street",
    "wet reflection",
    "traditional",
    "golden scales",
    "dynamic",
    "intricate",
    "line art",
    "plain background",
    "hard sci-fi",
    "metal texture",
    "japanese matsuri",
    "festive",
    "winter fantasy",
    "ice texture",
    "blue glow",
    "cozy still life",
    "nautical fantasy",
    "weathered wood",
    "storm waves",
    "macro delicate",
    "comic book art",
    "bold color",
    "high contrast",
    "asian landscape",
    "misty",
    "gothic romance",
    "pale glow",
    "classic still life",
    "gundam anime",
    "metallic armor",
    "moody landscape",
    "green tone",
    "retro photography",
    "film grain",
    "greek mythology",
    "wet texture",
    "classical",
    "middle eastern landscape",
    "silhouette",
    "street art",
    "bold lines",
    "dark background",
    "winter cartoon",
    "round shape",
    "classical theater",
    "rich color",
    "rustic fantasy",
    "mossy texture",
    "urban landscape",
    "golden glow",
    "transparent texture",
    "historical architecture",
    "ancient texture",
    "synthwave",
    "vaporwave",
    "neon grid",
    "retro 80s",
    "wildlife photo",
    "gentle",
    "natural green",
    "bohemian",
    "creative",
    "norse mythology",
    "lightning",
    "storm",
    "muscular",
    "japanese food photography",
    "green tone",
    "asian festival",
    "golden glow",
    "sci-fi robot",
    "rural landscape",
    "baroque",
    "intricate details",
    "minimalist landscape",
    "clear sky",
    "cute fantasy",
    "soft glow",
    "urban noir",
    "pet photography",
    "happy",
    "chinese traditional",
    "aged texture",
    "calligraphy",
    "antique",
    "volcanic fantasy",
    "fiery red",
    "rugged stone",
    "minimalist fashion",
    "natural light",
    "japanese myth",
    "feather cloak",
    "dessert photography",
    "delicate",
    "sweet",
    "futuristic architecture",
    "glass reflection",
    "bright light",
    "cursed glow",
    "graveyard",
    "spooky",
    "soft mist",
    "ink tone",
    "mid century modern",
    "wood texture",
    "cosmic glow",
    "dark background",
    "rural american",
    "natural texture",
    "anime supernatural",
    "energy glow",
    "classical greek art",
    "museum light",
    "tropical nature",
    "mist",
    "vibrant green",
    "luxury decor",
    "luxury",
    "japanese minimalist",
    "fantasy combat",
    "fire glow",
    "magic circle",
    "lifestyle photography",
    "macro fantasy",
    "intricate texture",
    "architectural photography",
    "clean lines",
    "japanese horror",
    "eerie glow",
    "bakery photography",
    "inviting",
    "fantasy celestial",
    "marble texture",
    "starry sky"
]

client = AsyncOpenAI(api_key=API_KEY, base_url=BASE_URL)

def build_prompt():
    styles = random.sample(STYLE_VOCAB, k=random.randint(3, 6))
    style_str = ", ".join(styles)

    return f"""
You are a data generator for creating Stable Diffusion training data.

Generate {BATCH_SIZE} entries in a valid JSON array. Each entry must follow this exact format:
{{
  "messages":[
    {{"role":"system","content":"You are a Stable Diffusion prompt engineer. Convert user input into concise comma-separated prompt keywords."}},
    {{"role":"user","content":"<natural user description>. Style: {style_str}"}},
    {{"role":"assistant","content":"<optimized comma-separated keywords>" }}
  ]
}}

Strict requirements:
1. The "user" content must be a natural, diverse English description. It must end with "Style: {style_str}".
2. The "assistant" content must be extremely concise. It may ONLY contain:
   - Core subject keywords extracted from the user description (1-3 words/phrases, no extra adjectives or details).
   - ALL style words exactly as provided in the user's "Style:" list (order may be slightly adjusted).
   No other words, adjectives, lighting terms, atmosphere, composition, or extra details are allowed.
3. Output must be a raw JSON array only. No explanations, no markdown code blocks, just the JSON array.
"""

async def fetch_batch():
    prompt = build_prompt()

    resp = await client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.9
    )

    text = resp.choices[0].message.content

    try:
        data = json.loads(text)
        return data
    except:
        return []


async def main():
    results = []
    seen = set()

    tasks = []

    for _ in range(TOTAL // BATCH_SIZE):
        tasks.append(fetch_batch())

        if len(tasks) >= CONCURRENCY:
            batch_results = await asyncio.gather(*tasks)
            tasks = []

            for batch in batch_results:
                for item in batch:
                    key = json.dumps(item)
                    if key not in seen:
                        seen.add(key)
                        results.append(item)

            print(f"Current count: {len(results)}")

    with open("dataset.json", "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print("Completion, total:", len(results))

if __name__ == "__main__":
    asyncio.run(main())